import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Card } from './Card';
import { Button } from './Button';
import { AIInsights } from './AIInsights';
import { db } from '../../services/mockDb';
import { X, TrendingUp, Users, Briefcase, BarChart } from 'lucide-react';

interface AIReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

type ReportType = 'revenue' | 'leads' | 'agents';

export const AIReportModal: React.FC<AIReportModalProps> = ({ isOpen, onClose }) => {
  const [activeTab, setActiveTab] = useState<ReportType>('revenue');
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (isOpen) {
      fetchData(activeTab);
    }
  }, [isOpen, activeTab]);

  const fetchData = async (type: ReportType) => {
    setLoading(true);
    let result;
    switch (type) {
      case 'revenue':
        // Fetch products/sales stats
        const products = await db.getProducts();
        const stats = await db.getStats();
        result = { products, stats };
        break;
      case 'leads':
        result = await db.getCustomers();
        break;
      case 'agents':
        result = await db.getAgents();
        break;
    }
    setData(result);
    setLoading(false);
  };

  const getPrompt = (type: ReportType) => {
    switch (type) {
      case 'revenue':
        return "Analyze the internal revenue streams based on property sales and listings. Identify key trends in pricing and sales velocity. Suggest strategies to increase internal revenue.";
      case 'leads':
        return "Analyze the current customer base. Segment leads by status and budget. Identify high-priority opportunities and suggest conversion tactics for 'Negotiation' status clients.";
      case 'agents':
        return "Evaluate the overall team performance. Compare sales counts, points generated, and commission payouts. Identify top performers and suggest incentive structures for underperforming agents.";
      default:
        return "";
    }
  };

  const tabs = [
    { id: 'revenue', label: 'Revenue', icon: <TrendingUp size={16} /> },
    { id: 'leads', label: 'Leads', icon: <Users size={16} /> },
    { id: 'agents', label: 'Team', icon: <Briefcase size={16} /> },
  ];

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[110] flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
          <motion.div
            initial={{ scale: 0.9, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.9, opacity: 0, y: 20 }}
            className="w-full max-w-3xl"
          >
            <Card className="bg-zinc-900 border border-white/10 shadow-2xl h-[600px] flex flex-col p-0 overflow-hidden" noTilt contentClassName="p-0 flex flex-col h-full">
              
              {/* Header */}
              <div className="p-4 border-b border-white/5 flex justify-between items-center bg-zinc-950/50">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-600 to-blue-900 flex items-center justify-center text-white shadow-lg shadow-blue-900/20">
                    <BarChart size={20} />
                  </div>
                  <div>
                    <h2 className="text-xl font-bold text-white font-display tracking-tight">AI Intelligence Report</h2>
                    <p className="text-xs text-zinc-500">Generated by Gemini 2.5 Flash</p>
                  </div>
                </div>
                <button onClick={onClose} className="text-zinc-500 hover:text-white transition-colors">
                  <X size={24} />
                </button>
              </div>

              <div className="flex flex-1 overflow-hidden">
                {/* Sidebar Tabs */}
                <div className="w-48 bg-zinc-950/30 border-r border-white/5 p-4 space-y-2">
                   <p className="text-[10px] font-bold uppercase tracking-widest text-zinc-600 mb-4">Report Type</p>
                   {tabs.map(tab => (
                     <button
                       key={tab.id}
                       onClick={() => setActiveTab(tab.id as ReportType)}
                       className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium transition-all ${
                         activeTab === tab.id 
                           ? 'bg-blue-600/10 text-blue-400 border border-blue-500/20 shadow-[0_0_15px_rgba(59,130,246,0.1)]' 
                           : 'text-zinc-500 hover:text-zinc-300 hover:bg-white/5 border border-transparent'
                       }`}
                     >
                       {tab.icon}
                       {tab.label}
                     </button>
                   ))}
                </div>

                {/* Content Area */}
                <div className="flex-1 p-6 overflow-y-auto bg-[#050505] relative">
                  {/* Background Grid */}
                  <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 pointer-events-none"></div>
                  
                  <div className="relative z-10">
                    <h3 className="text-2xl font-bold text-white mb-6 font-display flex items-center gap-2">
                       {tabs.find(t => t.id === activeTab)?.label} Analysis
                    </h3>

                    {loading ? (
                      <div className="flex flex-col items-center justify-center h-64">
                        <div className="w-8 h-8 border-2 border-blue-500 border-t-transparent rounded-full animate-spin mb-2"></div>
                        <span className="text-xs text-zinc-500 animate-pulse">Fetching Data...</span>
                      </div>
                    ) : (
                      <div className="space-y-6">
                        <AIInsights 
                          key={activeTab} // Force re-render on tab change
                          title={`${tabs.find(t => t.id === activeTab)?.label} Deep Dive`}
                          prompt={getPrompt(activeTab)}
                          data={data}
                          buttonText="Generate Report"
                          compact={false}
                        />
                        
                        <div className="p-4 rounded-xl bg-zinc-900/50 border border-white/5">
                           <h4 className="text-sm font-bold text-zinc-300 mb-2">Data Context</h4>
                           <p className="text-xs text-zinc-500">
                             This analysis is based on {activeTab === 'revenue' ? 'real-time sales data and product listings' : activeTab === 'leads' ? `${(data as any[])?.length || 0} customer records` : `${(data as any[])?.length || 0} agent profiles`}.
                           </p>
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </Card>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
